apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "${POSTGRES_PASSWORD}"
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true

  - name: MQTT
    type: grafana-mqtt-datasource
    uid: mqtt
    url: tcp://mqtt:1883
    jsonData:
      topics:
        - scarnergy/#
