_format_version: "2.1"
_transform: true

services:
  - name: scarnergy-auth
    url: http://auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1
        strip_path: true

  - name: scarnergy-rest
    url: http://rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1
        strip_path: true

  - name: scarnergy-realtime
    url: http://realtime:4000/socket
    routes:
      - name: realtime-route
        paths:
          - /realtime/v1
        strip_path: true

  - name: scarnergy-storage
    url: http://storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage/v1
        strip_path: true

  - name: scarnergy-meta
    url: http://meta:8080
    routes:
      - name: meta-route
        paths:
          - /meta
        strip_path: true

  - name: scarnergy-ai
    url: http://ai_server:8001
    routes:
      - name: ai-route
        paths:
          - /ai
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Encoding
        - Accept-Profile
        - Accept-Version
        - Authorization
        - Content-Length
        - Content-MD5
        - Content-Profile
        - Content-Type
        - Date
        - Prefer
        - Range
        - X-Auth-Token
        - X-CSRF-Token
        - X-Requested-With
        - apikey
        - x-client-info
        - x-supabase-api-version
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 86400

  - name: key-auth
    config:
      key_names:
        - apikey
        - api_key
        - ApiKey
        - Authorization
      key_in_header: true
      key_in_query: true
      key_in_body: false
      hide_credentials: true
      anonymous: anon

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjIwNTEyMTg4MDB9.r0GAZmnw3PcxO23v52N13u52lmWHIUYQ4LcaqcYd4b8}
  - username: service_role
    keyauth_credentials:
      - key: ${SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MjA1MTIxODgwMH0.awrZCFEvvrU75SNxtv2Lb3AK4PO7_AQu7oWoz23Z9eM}